[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#414347"
blue = "#77A3AB"
cyan = "#0BAAC9"
green = "#1DD361"
magenta = "#5350B9"
red = "#DE352E"
white = "#FFFFFF"
yellow = "#F3BD09"

[colors.normal]
black = "#1F1F1F"
blue = "#6480FF"
cyan = "#2AFFDC"
green = "#05FF56"
magenta = "#4E5AB7"
red = "#FF1F7B"
white = "#BDA9A9"
yellow = "#ECBA0F"

[colors.primary]
background = "#131313"
foreground = "#D6DBE5"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = '1.0'

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"

[scrolling]
history = 10000
multiplier = 3

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
